import YAML from 'yaml';
import { AgentManifest, type CiFile, type CiTarget, type CiTrigger } from '@devdigest/shared';
import { AppError } from '../../platform/errors.js';

/**
 * L06 Export to CI - the pure half.
 *
 * `buildBundle` turns an agent into the files that agent IS as configuration.
 * It performs no I/O, takes no clock and no DI, and is deterministic: the same
 * agent and options produce byte-identical files (spec L06-export-ci AC-15).
 * Everything that needs a database lives in `service.ts`.
 *
 * The manifest is emitted with the `yaml` library rather than a hand-rolled
 * serializer on purpose. A system prompt is untrusted, arbitrary, multi-line
 * text, and the cases that break naive block-scalar emission are not exotic:
 * content whose first line is indented needs an explicit indentation indicator
 * (`|2-`), content with trailing newlines needs a keep chomping indicator
 * (`|+`), and content with tabs or CRLF cannot be a literal block at all and
 * must fall back to a quoted scalar. Getting any of those wrong produces a file
 * the user commits and only discovers is corrupt later.
 */

/** Total generated bytes above which a bundle is refused (spec: non-functional). */
export const MAX_BUNDLE_BYTES = 512 * 1024;

const MANIFEST_DIR = '.devdigest/agents';
const SKILL_DIR = '.devdigest/skills';
const WORKFLOW_PATH = '.github/workflows/devdigest-review.yml';

/** Emitted verbatim into the workflow; kept out of the template literal so the
 *  `${{ … }}` GitHub expression is never read as a JS interpolation. */
const GITHUB_TOKEN_EXPR = '${{ secrets.GITHUB_TOKEN }}';

/** Canonical trigger order, so two bundles differing only in click order match. */
const TRIGGER_ORDER: readonly CiTrigger[] = ['opened', 'synchronize', 'reopened'];

export interface BundleAgent {
  name: string;
  provider: 'openai' | 'anthropic' | 'openrouter';
  model: string;
  system_prompt: string;
  strategy: 'auto' | 'single-pass' | 'map-reduce';
  ci_fail_on: 'never' | 'critical' | 'warning' | 'any';
}

export interface BundleSkill {
  name: string;
  body: string;
  enabled: boolean;
}

export interface BundleOptions {
  target: CiTarget;
  triggers: CiTrigger[];
  post_as: 'github_review' | 'pr_comment' | 'none';
}

/**
 * Name -> path segment, by ALLOW-LIST rather than by escaping.
 *
 * Everything outside `[a-z0-9]` collapses to a single dash, so `../`, a leading
 * slash, a path separator and a null byte cannot survive into a generated path
 * - there is no escape sequence to get wrong because nothing is escaped.
 * A name made entirely of punctuation or emoji reduces to the empty string, so
 * the caller's `fallback` becomes the slug.
 */
export function slugify(name: string, fallback: string): string {
  const slug = name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
    .replace(/-+$/g, '');
  return slug || fallback;
}

/**
 * Slugs for a list of names, disambiguated in list order.
 *
 * "Secret Leakage Gate" and "secret-leakage gate" both reduce to
 * `secret-leakage-gate`; without this the second file would silently overwrite
 * the first and the manifest would point at contents that are not the skill's.
 */
export function uniqueSlugs(names: string[], fallback: string): string[] {
  const seen = new Map<string, number>();
  return names.map((name) => {
    const base = slugify(name, fallback);
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    return n === 0 ? base : `${base}-${n + 1}`;
  });
}

/**
 * The agent as an `AgentManifest` YAML document.
 *
 * The object is validated BEFORE serialization (so a malformed agent fails
 * here, not in the user's repository) and the emitted text is parsed back and
 * re-validated AFTER (so a prompt that the serializer could not represent
 * faithfully fails here too, rather than becoming a corrupt committed file).
 */
export function agentYaml(agent: BundleAgent, skillSlugs: string[]): string {
  const manifest = AgentManifest.parse({
    name: agent.name,
    provider: agent.provider,
    model: agent.model,
    system_prompt: agent.system_prompt,
    skills: skillSlugs,
    strategy: agent.strategy,
    ci_fail_on: agent.ci_fail_on,
  });

  const header =
    '# The agent, as configuration. Generated by DevDigest (Export to CI).\n' +
    '# This file is the agent: model, prompt, skills and gate policy. Commit it\n' +
    '# next to the code it reviews so the definition is readable and diffable.\n';
  const text = header + YAML.stringify(manifest, { lineWidth: 0 });

  const roundTripped = AgentManifest.parse(YAML.parse(text));
  if (roundTripped.system_prompt !== manifest.system_prompt) {
    throw new AppError(
      'manifest_not_representable',
      'The agent’s system prompt could not be written to YAML without changing it.',
      500,
    );
  }
  return text;
}

/**
 * The GitHub Actions workflow.
 *
 * Its review step is a PLACEHOLDER and says so, at length, in a comment. There
 * is no runner: `mcp/bin/devdigest` implements only `--mode working` and
 * reaches the DevDigest API over HTTP, which a GitHub-hosted runner cannot do
 * against a local-first server. Emitting a step that looks like it works would
 * be worse than emitting one that admits it does not (spec AC-17).
 */
export function workflowYaml(manifestPath: string, options: BundleOptions): string {
  const types = TRIGGER_ORDER.filter((t) => options.triggers.includes(t));
  return `# Generated by DevDigest - Export to CI.
#
# WHAT THIS DOES TODAY: nothing yet. The review step below is a PLACEHOLDER.
# DevDigest generates the agent definition; it does not yet ship a runner that
# executes a review inside CI. Replace that step with your own invocation.
#
# The file that matters is the manifest:
#   ${manifestPath}
# It IS the agent - model, prompt, skills and gate policy - and it is what a
# runner reads. Committing it is what makes the agent shared and diffable.
#
# Regenerate: DevDigest -> Agents -> the agent -> CI -> Export to CI.
name: DevDigest Review

on:
  pull_request:
    types: [${types.join(', ')}]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # PLACEHOLDER. Swap this for the command that runs your reviewer. It
      # should read $DEVDIGEST_AGENT, review the pull request diff, post results
      # per $DEVDIGEST_POST_AS, and exit non-zero when a finding reaches
      # $DEVDIGEST_FAIL_ON.
      - name: Run DevDigest review
        env:
          DEVDIGEST_AGENT: ${manifestPath}
          DEVDIGEST_POST_AS: ${options.post_as}
          GITHUB_TOKEN: ${GITHUB_TOKEN_EXPR}
        run: |
          echo "DevDigest: no runner is configured for this workflow yet."
          echo "Agent manifest: $DEVDIGEST_AGENT"
          echo "Replace this step to run a real review."
`;
}

/**
 * The whole bundle, in preview order: the workflow first (it is what the user
 * came to see), then the manifest, then one file per enabled skill.
 */
export function buildBundle(
  agent: BundleAgent,
  skills: BundleSkill[],
  options: BundleOptions,
): CiFile[] {
  if (options.target !== 'gha') {
    throw new AppError(
      'unsupported_ci_target',
      `Only GitHub Actions is available today; "${options.target}" is not yet supported.`,
      400,
    );
  }

  const enabled = skills.filter((s) => s.enabled);
  const skillSlugs = uniqueSlugs(
    enabled.map((s) => s.name),
    'skill',
  );
  const agentSlug = slugify(agent.name, 'agent');
  const manifestPath = `${MANIFEST_DIR}/${agentSlug}.yaml`;

  const files: CiFile[] = [
    { path: WORKFLOW_PATH, contents: workflowYaml(manifestPath, options), editable: true },
    { path: manifestPath, contents: agentYaml(agent, skillSlugs), editable: true },
    ...enabled.map((skill, i) => ({
      path: `${SKILL_DIR}/${skillSlugs[i]}.md`,
      contents: skill.body,
      editable: true,
    })),
  ];

  const bytes = files.reduce((n, f) => n + Buffer.byteLength(f.contents, 'utf8'), 0);
  if (bytes > MAX_BUNDLE_BYTES) {
    throw new AppError(
      'bundle_too_large',
      `The generated bundle is ${Math.round(bytes / 1024)} KB, over the ${Math.round(
        MAX_BUNDLE_BYTES / 1024,
      )} KB limit. Shorten the system prompt or the skill bodies.`,
      413,
    );
  }
  return files;
}
