import YAML from 'yaml';
import { AgentManifest, type CiFile, type CiTarget, type CiTrigger } from '@devdigest/shared';
import { AppError } from '../../platform/errors.js';

/**
 * L06 Export to CI - the pure half.
 *
 * `buildBundle` turns an agent into the files that agent IS as configuration.
 * It performs no I/O, takes no clock and no DI, and is deterministic: the same
 * agent and options produce byte-identical files (spec L06-export-ci AC-15).
 * Everything that needs a database lives in `service.ts`.
 *
 * The manifest is emitted with the `yaml` library rather than a hand-rolled
 * serializer on purpose. A system prompt is untrusted, arbitrary, multi-line
 * text, and the cases that break naive block-scalar emission are not exotic:
 * content whose first line is indented needs an explicit indentation indicator
 * (`|2-`), content with trailing newlines needs a keep chomping indicator
 * (`|+`), and content with tabs or CRLF cannot be a literal block at all and
 * must fall back to a quoted scalar. Getting any of those wrong produces a file
 * the user commits and only discovers is corrupt later.
 */

/** Total generated bytes above which a bundle is refused (spec: non-functional). */
export const MAX_BUNDLE_BYTES = 512 * 1024;

const MANIFEST_DIR = '.devdigest/agents';
const SKILL_DIR = '.devdigest/skills';
const WORKFLOW_PATH = '.github/workflows/devdigest-review.yml';

/**
 * GitHub Actions expressions, emitted VERBATIM into the workflow.
 *
 * They live in constants rather than inside the template literal because
 * `${{ … }}` and a JS `${ … }` are one character apart: written inline, a
 * `${{ github.repository }}` would be read as a JS interpolation of an
 * undefined `{ github.repository }` and fail to compile - or worse, compile.
 */
const PR_HEAD_SHA_EXPR = '${{ github.event.pull_request.head.sha }}';
const PR_BASE_REF_EXPR = '${{ github.event.pull_request.base.ref }}';
const PR_NUMBER_EXPR = '${{ github.event.pull_request.number }}';
const REPOSITORY_EXPR = '${{ github.repository }}';
/** A repository variable, not a secret: an API base URL is not confidential. */
const API_URL_EXPR = '${{ vars.DEVDIGEST_API_URL }}';

/** Canonical trigger order, so two bundles differing only in click order match. */
const TRIGGER_ORDER: readonly CiTrigger[] = ['opened', 'synchronize', 'reopened'];

export interface BundleAgent {
  /** The agent's uuid. `agents` has no slug column, so this is what CI passes. */
  id: string;
  name: string;
  provider: 'openai' | 'anthropic' | 'openrouter';
  model: string;
  system_prompt: string;
  strategy: 'auto' | 'single-pass' | 'map-reduce';
  ci_fail_on: 'never' | 'critical' | 'warning' | 'any';
}

export interface BundleSkill {
  name: string;
  body: string;
  enabled: boolean;
}

export interface BundleOptions {
  target: CiTarget;
  triggers: CiTrigger[];
  post_as: 'github_review' | 'pr_comment' | 'none';
}

/**
 * Name -> path segment, by ALLOW-LIST rather than by escaping.
 *
 * Everything outside `[a-z0-9]` collapses to a single dash, so `../`, a leading
 * slash, a path separator and a null byte cannot survive into a generated path
 * - there is no escape sequence to get wrong because nothing is escaped.
 * A name made entirely of punctuation or emoji reduces to the empty string, so
 * the caller's `fallback` becomes the slug.
 */
export function slugify(name: string, fallback: string): string {
  const slug = name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
    .replace(/-+$/g, '');
  return slug || fallback;
}

/**
 * Slugs for a list of names, disambiguated in list order.
 *
 * "Secret Leakage Gate" and "secret-leakage gate" both reduce to
 * `secret-leakage-gate`; without this the second file would silently overwrite
 * the first and the manifest would point at contents that are not the skill's.
 */
export function uniqueSlugs(names: string[], fallback: string): string[] {
  const seen = new Map<string, number>();
  return names.map((name) => {
    const base = slugify(name, fallback);
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    return n === 0 ? base : `${base}-${n + 1}`;
  });
}

/**
 * The agent as an `AgentManifest` YAML document.
 *
 * The object is validated BEFORE serialization (so a malformed agent fails
 * here, not in the user's repository) and the emitted text is parsed back and
 * re-validated AFTER (so a prompt that the serializer could not represent
 * faithfully fails here too, rather than becoming a corrupt committed file).
 */
export function agentYaml(agent: BundleAgent, skillSlugs: string[]): string {
  const manifest = AgentManifest.parse({
    name: agent.name,
    provider: agent.provider,
    model: agent.model,
    system_prompt: agent.system_prompt,
    skills: skillSlugs,
    strategy: agent.strategy,
    ci_fail_on: agent.ci_fail_on,
  });

  const header =
    '# The agent, as configuration. Generated by DevDigest (Export to CI).\n' +
    '# This file is the agent: model, prompt, skills and gate policy. Commit it\n' +
    '# next to the code it reviews so the definition is readable and diffable.\n';
  const text = header + YAML.stringify(manifest, { lineWidth: 0 });

  const roundTripped = AgentManifest.parse(YAML.parse(text));
  if (roundTripped.system_prompt !== manifest.system_prompt) {
    throw new AppError(
      'manifest_not_representable',
      'The agent’s system prompt could not be written to YAML without changing it.',
      500,
    );
  }
  return text;
}

/**
 * The GitHub Actions workflow.
 *
 * It runs on a SELF-HOSTED runner (labels `self-hosted` + `devdigest`) because
 * the review happens in DevDigest, which is a local-first server a
 * GitHub-hosted runner cannot reach. The runner only computes the diff and
 * calls the CLI; the SERVER reviews it, posts the review with the user's own
 * GitHub credentials and records the run. Two consequences are visible in the
 * file: `permissions` is read-only, and no secret of any kind appears in it.
 *
 * Nothing model-authored or user-authored is interpolated into the `run:`
 * block - the only two values that vary are the agent's uuid and a `post_as`
 * enum, both from closed sets. Everything else the step needs arrives through
 * `env:` as a GitHub expression, so no value flows through a shell in a way
 * that could be quoted wrong.
 */
export function workflowYaml(
  manifestPath: string,
  agentId: string,
  options: BundleOptions,
): string {
  const types = TRIGGER_ORDER.filter((t) => options.triggers.includes(t));
  return `# Generated by DevDigest - Export to CI.
#
# WHAT THIS NEEDS: a self-hosted runner labelled \`devdigest\` on a machine that
# can reach your DevDigest API, with the \`devdigest\` CLI on its PATH (override
# with $DEVDIGEST_CLI) and DEVDIGEST_API_URL set as a repository variable if the
# API is not on http://localhost:3001.
#
# The runner never holds a model key or a GitHub token: it computes the diff and
# hands it to DevDigest, which reviews it, posts the review as you, and records
# the run. That is why \`permissions\` below is read-only.
#
# SELF-HOSTED RUNNERS BELONG ON PRIVATE REPOSITORIES. On a public one anyone who
# can open a pull request can run their code on your machine - GitHub's own
# guidance, not ours.
#
# The file that matters is the manifest:
#   ${manifestPath}
# It IS the agent - model, prompt, skills and gate policy - and it is what the
# review runs. Committing it is what makes the agent shared and diffable.
#
# Regenerate: DevDigest -> Agents -> the agent -> CI -> Export to CI.
name: DevDigest Review

on:
  pull_request:
    types: [${types.join(', ')}]

# Read-only on purpose: the review is posted by the DevDigest server, not by
# this workflow, so nothing here needs write access to the repository.
permissions:
  contents: read

jobs:
  review:
    runs-on: [self-hosted, devdigest]
    steps:
      - uses: actions/checkout@v4
        with:
          # The PR HEAD rather than the merge commit, and the whole history:
          # the review diffs against the merge base with the target branch.
          ref: ${PR_HEAD_SHA_EXPR}
          fetch-depth: 0

      - name: Run DevDigest review
        env:
          DEVDIGEST_API_URL: ${API_URL_EXPR}
          DEVDIGEST_BASE: ${PR_BASE_REF_EXPR}
          DEVDIGEST_PR: ${PR_NUMBER_EXPR}
          DEVDIGEST_REPO: ${REPOSITORY_EXPR}
        run: |
          "\${DEVDIGEST_CLI:-devdigest}" review \\
            --mode branch \\
            --base "$DEVDIGEST_BASE" \\
            --repo "$DEVDIGEST_REPO" \\
            --pr "$DEVDIGEST_PR" \\
            --agent ${agentId} \\
            --post-as ${options.post_as} \\
            --ci-result devdigest-result.json

      # Always, so a blocked review still leaves its counts behind.
      - name: Upload the run summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devdigest-result
          path: devdigest-result.json
          if-no-files-found: ignore
`;
}

/**
 * The whole bundle, in preview order: the workflow first (it is what the user
 * came to see), then the manifest, then one file per enabled skill.
 */
export function buildBundle(
  agent: BundleAgent,
  skills: BundleSkill[],
  options: BundleOptions,
): CiFile[] {
  if (options.target !== 'gha') {
    throw new AppError(
      'unsupported_ci_target',
      `Only GitHub Actions is available today; "${options.target}" is not yet supported.`,
      400,
    );
  }

  const enabled = skills.filter((s) => s.enabled);
  const skillSlugs = uniqueSlugs(
    enabled.map((s) => s.name),
    'skill',
  );
  const agentSlug = slugify(agent.name, 'agent');
  const manifestPath = `${MANIFEST_DIR}/${agentSlug}.yaml`;

  const files: CiFile[] = [
    {
      path: WORKFLOW_PATH,
      contents: workflowYaml(manifestPath, agent.id, options),
      editable: true,
    },
    { path: manifestPath, contents: agentYaml(agent, skillSlugs), editable: true },
    ...enabled.map((skill, i) => ({
      path: `${SKILL_DIR}/${skillSlugs[i]}.md`,
      contents: skill.body,
      editable: true,
    })),
  ];

  const bytes = files.reduce((n, f) => n + Buffer.byteLength(f.contents, 'utf8'), 0);
  if (bytes > MAX_BUNDLE_BYTES) {
    throw new AppError(
      'bundle_too_large',
      `The generated bundle is ${Math.round(bytes / 1024)} KB, over the ${Math.round(
        MAX_BUNDLE_BYTES / 1024,
      )} KB limit. Shorten the system prompt or the skill bodies.`,
      413,
    );
  }
  return files;
}
