import type { CiFailOn, RepoRef, Severity } from '@devdigest/shared';

/**
 * CI module constants and the pure helpers two layers of this module share.
 *
 * Nothing here does I/O or takes the container: `parseRepoRef` is the single
 * place an untrusted `owner/name` string becomes a `RepoRef` that reaches a
 * GitHub API path.
 */

/** Branch the generated files are committed to, and the PR's head. */
export const CI_BRANCH = 'devdigest/ci';

/** Title of the pull request that installs the agent into a repository. */
export const CI_PR_TITLE = 'Add DevDigest CI review';

/** Commit message for the one atomic commit `commitFiles` writes. */
export const CI_COMMIT_MESSAGE = 'chore(devdigest): add CI review workflow and agent manifest';

/** Body of the installation pull request. Fixed text - no user input reaches it. */
export const CI_PR_BODY =
  'Generated by DevDigest (Export to CI).\n\n' +
  'This pull request adds the agent as configuration: a GitHub Actions workflow, ' +
  'the agent manifest and one file per enabled skill. The workflow runs on a ' +
  'self-hosted runner labelled `devdigest`, which reaches your local DevDigest ' +
  'API; review posting happens server-side, so the workflow needs no write ' +
  'permission and no model key.\n';

/**
 * `owner/name` -> `RepoRef`, by ALLOW-LIST rather than by escaping.
 *
 * The value arrives from an API body and ends up interpolated into a GitHub
 * REST path, so anything that is not exactly two segments of GitHub's own name
 * alphabet is refused outright: there is no traversal sequence to get wrong
 * because nothing is escaped. `.` and `..` are rejected explicitly - they are
 * legal-looking repository names that are not.
 */
const OWNER = /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$/;
const NAME = /^[A-Za-z0-9._-]{1,100}$/;

export function parseRepoRef(repo: string): RepoRef | null {
  const parts = repo.trim().split('/');
  if (parts.length !== 2) return null;
  const [owner, name] = parts as [string, string];
  if (!OWNER.test(owner)) return null;
  if (!NAME.test(name) || name === '.' || name === '..') return null;
  return { owner, name };
}

/**
 * Rows `GET /ci-runs` returns at most.
 *
 * A cap, not a page size: the CI Runs page filters client-side, so the list it
 * receives IS the data set. `ci_runs` carries no index beyond its primary key,
 * which is what makes an unbounded read a problem worth naming here.
 */
export const CI_RUNS_PAGE_LIMIT = 200;

/**
 * `CiFailOn` (the agent's gate policy) -> `Severity` (what `reviewDiff` takes).
 *
 * The two enums are deliberately different: a gate is a policy with an "off"
 * setting, a severity is a level. `never` therefore has no severity at all, and
 * `undefined` is the honest answer - `reviewDiff` reads that as "the agent's own
 * gate decides", which for `never` yields no blockers. `any` maps to the lowest
 * severity there is, so every finding blocks.
 */
export function failOnToSeverity(ciFailOn: CiFailOn): Severity | undefined {
  switch (ciFailOn) {
    case 'never':
      return undefined;
    case 'critical':
      return 'CRITICAL';
    case 'warning':
      return 'WARNING';
    case 'any':
      return 'SUGGESTION';
  }
}
