import type { CSSProperties } from "react";

export const s = {
  wrap: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    height: "100%",
    overflowY: "auto",
  } satisfies CSSProperties,
  layout: (narrow: boolean) =>
    ({
      display: "grid",
      gridTemplateColumns: narrow ? "1fr" : "1fr 220px",
      gap: 24,
      alignItems: "start",
      padding: "20px 24px 48px",
    }) satisfies CSSProperties,
  column: { display: "flex", flexDirection: "column", gap: 14, minWidth: 0 } satisfies CSSProperties,

  // ---- header ----
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "14px 16px",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  } satisfies CSSProperties,
  headerTop: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  headerTitle: {
    fontSize: 15,
    fontWeight: 650,
    color: "var(--text-primary)",
    flex: 1,
    minWidth: 160,
  } satisfies CSSProperties,
  meta: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  metaSep: { color: "var(--text-muted)" } satisfies CSSProperties,
  cost: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  reason: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,

  // ---- page nav ----
  nav: {
    position: "sticky",
    top: 12,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "12px 10px",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  } satisfies CSSProperties,
  navLabel: {
    fontSize: 11,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  navItem: {
    display: "block",
    width: "100%",
    textAlign: "left",
    background: "none",
    border: "none",
    padding: "5px 6px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,

  // ---- section card ----
  card: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
  } satisfies CSSProperties,
  cardHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "12px 14px",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  cardTitle: {
    fontSize: 14,
    fontWeight: 650,
    color: "var(--text-primary)",
    flex: 1,
    minWidth: 0,
    outline: "none",
  } satisfies CSSProperties,
  cardBody: {
    padding: "0 14px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  marker: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-secondary)",
    fontStyle: "italic",
  } satisfies CSSProperties,

  // ---- rows ----
  rows: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    listStyle: "none",
    margin: 0,
    padding: 0,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 10px",
    background: "var(--bg-primary)",
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  ordinal: {
    fontSize: 12,
    color: "var(--text-muted)",
    minWidth: 18,
    flexShrink: 0,
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 3 } satisfies CSSProperties,
  rowPath: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowReason: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  command: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    margin: 0,
  } satisfies CSSProperties,
  rowMeta: { fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  links: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    fontSize: 12.5,
  } satisfies CSSProperties,
  /** Containing block for `srOnly`, which would otherwise resolve against the
      document and give the page an outer scrollbar. See CopyButton. */
  copyWrap: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
  } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
};
