import type { CSSProperties } from "react";

/** Shared styles for the agent and skill Context tabs. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  h2: { fontSize: 17, fontWeight: 700 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 190,
  } satisfies CSSProperties,
  filterIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  groupLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "18px 0 8px",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (attached: boolean, muted: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid " + (attached ? "var(--border-strong)" : "var(--border)"),
    background: attached ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: muted ? 0.7 : 1,
  }),
  rowDir: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  rowName: { fontSize: 13, color: "var(--text-primary)" } satisfies CSSProperties,
  rowSpacer: { flex: 1 } satisfies CSSProperties,
  arrows: { display: "flex", gap: 2 } satisfies CSSProperties,
  arrowBtn: (disabled: boolean): CSSProperties => ({
    width: 26,
    height: 26,
    display: "inline-grid",
    placeItems: "center",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    color: disabled ? "var(--text-muted)" : "var(--text-secondary)",
    opacity: disabled ? 0.45 : 1,
    cursor: disabled ? "not-allowed" : "pointer",
  }),
  noMatch: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px",
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  footer: {
    marginTop: 18,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    fontSize: 13,
  } satisfies CSSProperties,
  footerWarn: { color: "var(--warn)", fontWeight: 600 } satisfies CSSProperties,
  footerOk: { color: "var(--text-muted)" } satisfies CSSProperties,
  manifest: {
    marginTop: 18,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
};
