#!/usr/bin/env bash
# Regenerate `.claude/repo-facts.md` - the structural card every subagent reads
# instead of re-deriving the repo layout from five files each time.
#
#   ./scripts/repo-facts.sh
#
# Machine-derived sections come from package.json, the dependency-cruiser
# configs, and the directory listings, so they cannot drift. The short prose
# sections live in this script, which makes them a single edit point.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=.claude/repo-facts.md

scripts_of() {
  python3 -c "
import json,sys
s = json.load(open('$1/package.json')).get('scripts', {})
print(' · '.join(f'\`{k}\`' for k in s))
"
}

rules_of() { grep -o "name: '[^']*'" "$1" | sed "s/name: '//;s/'//" | paste -sd, - | sed 's/,/, /g'; }

{
  cat <<'HEADER'
# Repo facts

GENERATED by `scripts/repo-facts.sh`. Do not edit by hand.

Read this first, before opening `AGENTS.md`, `TESTING.md`, or any package file.
It carries the structural facts an agent would otherwise re-derive on every run.
It does NOT replace `INSIGHTS.md` (module lessons) or a package's `AGENTS.md`
(conventions and rationale) - open those when the task actually touches them.

## Packages

Five standalone packages, no workspace. Each has its own `package.json` and
lockfile; cross-package code is shared only through tsconfig path aliases.

HEADER

  printf '| Package | Name | Scripts |\n|---|---|---|\n'
  for p in server client reviewer-core mcp e2e; do
    name=$(python3 -c "import json;print(json.load(open('$p/package.json'))['name'])")
    printf '| `%s/` | `%s` | %s |\n' "$p" "$name" "$(scripts_of $p)"
  done

  cat <<'LANES'

**`reviewer-core` and `e2e` use `npm`, not `pnpm`**; `server/`, `client/` and
`mcp/` use `pnpm`. `server/`, `reviewer-core/` and `mcp/` have NO `lint`
script; their mechanical boundary check is `arch:check`.

`mcp/` is also the only package on `zod` 4 - everything else is on `zod` 3,
which is why it aliases no shared contracts and has no `paths` block.

## Test lanes

| Lane | Command |
|---|---|
| server unit (hermetic) | `cd server && pnpm exec vitest run --exclude '**/*.it.test.ts'` |
| server integration (Docker) | `cd server && pnpm exec vitest run .it.test --no-file-parallelism` |
| reviewer-core | `cd reviewer-core && npm test` |
| client | `cd client && pnpm test` |
| mcp (hermetic) | `cd mcp && pnpm test` |
| mcp live stack (opt-in, not in CI) | `cd mcp && pnpm test:it` (needs `./scripts/dev.sh --no-client`) |
| browser e2e | `./scripts/e2e.sh` |

A server test importing `test/helpers/pg.ts` MUST be named `*.it.test.ts`, and
so must an mcp test that needs a live API.

## Server modules
LANES

  printf '\n`server/src/modules/`: '
  ls -d server/src/modules/*/ 2>/dev/null | xargs -n1 basename | paste -sd, - | sed 's/,/, /g'
  printf '\nRegistered statically in `server/src/modules/index.ts` (one import + one entry).\n'
  printf 'Shared helpers live in `modules/_shared/`: '
  ls server/src/modules/_shared/*.ts | xargs -n1 basename | paste -sd, - | sed 's/,/, /g'

  cat <<'BOUNDARIES'

## Mechanical boundary rules

A rule name below is what `arch:check` prints when it fires. Never widen a rule
or add an allowlist entry to fix a violation - fix the placement.

BOUNDARIES

  printf '| Config | Rules |\n|---|---|\n'
  printf '| `server/.dependency-cruiser.cjs` | %s |\n' "$(rules_of server/.dependency-cruiser.cjs)"
  printf '| `reviewer-core/.dependency-cruiser.cjs` | %s |\n' "$(rules_of reviewer-core/.dependency-cruiser.cjs)"
  printf '| `mcp/.dependency-cruiser.cjs` | %s |\n' "$(rules_of mcp/.dependency-cruiser.cjs)"

  cat <<'CONTRACTS'

`no-cross-module-imports` exempts only another module's `service.ts`,
`types.ts`, or `constants.ts`. Anything else shared between modules belongs in
`modules/_shared/`.

## Contracts, in two physical copies

`server/src/vendor/shared` is canonical; `client/src/vendor/shared` is the
client's own copy. A contract change lands in BOTH in the same step, or the two
sides drift silently. There is no sync script.

CONTRACTS

  printf 'Files under `contracts/`: '
  ls server/src/vendor/shared/contracts/*.ts | xargs -n1 basename | paste -sd, - | sed 's/,/, /g'
  printf '\n\nAlready drifted, pre-existing, do not "fix" as a side quest: '
  for f in adapters.ts contracts/eval-ci.ts contracts/knowledge.ts contracts/productionize.ts; do
    if ! diff -q "server/src/vendor/shared/$f" "client/src/vendor/shared/$f" >/dev/null 2>&1; then
      printf '`%s` ' "$f"
    fi
  done
  printf '\n\nVerify a change with `diff -q` on the files you touched, never a\n'
  printf 'whole-tree comparison - that is always red because of the drift above.\n'

  cat <<'FOOTER'

## Do not touch

- `server/clones/**` - runtime checkouts of imported repos
- `server/src/db/migrations/**` - generated; edit `db/schema/*.ts` then `pnpm db:generate`
- `client/src/vendor/ui/**` - vendored UI kit
- `.env` files - edit `.env.example` instead
- `CHANGELOG.md` and anything marked auto-generated
- never `docker compose down -v` (destroys the dev database volume)

`CLAUDE.md` is a SYMLINK to `AGENTS.md` at the root and in `server/`,
`client/`, `reviewer-core/` and `e2e/`. There is one file per scope; edit
`AGENTS.md`.

## Environment traps

- The default `node` on this machine is v17 and breaks `pnpm` and `vitest`.
  Prepend `$HOME/.nvm/versions/node/v22.18.0/bin` to `PATH` before any of them.
- `pnpm db:generate` turns interactive and hangs on piped stdin when one table
  both gains and drops columns. Keep a migration additive, or split the edit.
  Never pipe stdin into it.
- The integration lane starts one Postgres container per file. Run it with
  `--no-file-parallelism`.
- An integration test that omits a provider from `overrides.llm` is NOT
  hermetic: the container falls back to `~/.devdigest/secrets.json` and makes
  real, billable calls. Pass `secrets: new MockSecretsProvider({})` too.
FOOTER
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
