import type { CSSProperties } from "react";

/** Co-located styles for ExportCiWizard. */
export const s = {
  steps: { padding: "18px 24px 4px" } satisfies CSSProperties,
  body: { padding: "18px 24px 24px" } satisfies CSSProperties,
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  } satisfies CSSProperties,
  tile: (selected: boolean, enabled: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
    textAlign: "left",
    padding: "14px 16px",
    borderRadius: 10,
    background: selected ? "var(--accent-soft, var(--bg-elevated))" : "var(--bg-surface)",
    border: `1px solid ${selected ? "var(--accent)" : "var(--border)"}`,
    opacity: enabled ? 1 : 0.45,
    cursor: enabled ? "pointer" : "not-allowed",
    font: "inherit",
    color: "inherit",
  }),
  tileHead: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    width: "100%",
  } satisfies CSSProperties,
  tileName: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  tileDesc: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  tag: {
    marginLeft: "auto",
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.03em",
    padding: "2px 7px",
    borderRadius: 99,
    background: "var(--accent)",
    color: "#fff",
  } satisfies CSSProperties,
  tagMuted: {
    marginLeft: "auto",
    fontSize: 10.5,
    fontWeight: 600,
    padding: "2px 7px",
    borderRadius: 99,
    background: "var(--bg-elevated)",
    color: "var(--text-muted)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 9,
  } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 6 } satisfies CSSProperties,
  chip: (on: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 11px",
    borderRadius: 7,
    fontSize: 12.5,
    font: "inherit",
    fontWeight: 500,
    cursor: "pointer",
    background: on ? "var(--accent-soft, var(--bg-elevated))" : "var(--bg-surface)",
    border: `1px solid ${on ? "var(--accent)" : "var(--border)"}`,
    color: on ? "var(--accent)" : "var(--text-secondary)",
  }),
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 20 } satisfies CSSProperties,
  radios: { display: "flex", flexDirection: "column", gap: 9 } satisfies CSSProperties,
  radio: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    fontSize: 13,
    cursor: "pointer",
  } satisfies CSSProperties,
  preview: {
    display: "grid",
    gridTemplateColumns: "minmax(200px, 260px) 1fr",
    gap: 14,
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    minHeight: 220,
  } satisfies CSSProperties,
  fileList: {
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    padding: 8,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    overflow: "auto",
    maxHeight: 260,
  } satisfies CSSProperties,
  fileBtn: (on: boolean): CSSProperties => ({
    textAlign: "left",
    padding: "7px 9px",
    borderRadius: 6,
    border: "none",
    background: on ? "var(--accent-soft, var(--bg-elevated))" : "transparent",
    color: on ? "var(--text-primary)" : "var(--text-secondary)",
    fontSize: 11.5,
    fontFamily: "var(--font-mono, monospace)",
    lineHeight: 1.45,
    cursor: "pointer",
    wordBreak: "break-all",
  }),
  pane: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  paneHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 12px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  panePath: {
    fontSize: 11.5,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  paneActions: { marginLeft: "auto", display: "flex", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  code: {
    margin: 0,
    padding: 12,
    overflow: "auto",
    maxHeight: 260,
    fontSize: 11.5,
    lineHeight: 1.55,
    fontFamily: "var(--font-mono, monospace)",
    whiteSpace: "pre",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  note: {
    display: "flex",
    gap: 9,
    alignItems: "flex-start",
    marginTop: 14,
    padding: "11px 13px",
    borderRadius: 8,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  noteTop: {
    display: "flex",
    gap: 9,
    alignItems: "flex-start",
    marginBottom: 12,
    padding: "11px 13px",
    borderRadius: 8,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  noteTitle: { fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  error: {
    fontSize: 12.5,
    color: "var(--danger, #ef4444)",
    marginTop: 12,
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  spacer: { marginLeft: "auto" } satisfies CSSProperties,
};
